version: "2"
services:
  cms-utilization-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node
  cms-utilization-search-loader:
    image: sudowing/cms-utilization-search:master

    restart: always
    environment:
      ES_SERVICE_HOST: cms-utilization-search
      ES_SERVICE_PORT: 9200
    volumes:
      - ./volumes/elastic_exports:/tmp/elastic_exports
    depends_on:
    - cms-utilization-search
