version: "2"
services:
  cms-utilization-search:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/elastic:/usr/share/elasticsearch/data
    environment:
      discovery.type: single-node